#!/usr/bin/env python3
"""Generate the frontend's bundled i18n catalogs from the backend YAML.

``backend/config/i18n/{lang}.yaml`` is the single source of truth for
every UI string. The backend serves it at ``GET /api/i18n/{lang}``, but
the GitHub Pages PWA has no backend - so without a bundled copy every
string falls back to its inline German default and switching the
language does nothing.

The generated JSON is committed, exactly like ``install.sh``: the
frontend build (``npm ci && npm run build`` on CI) runs Node only, so
generating at build time would mean putting Python into the deploy
workflow. Committing the artifact keeps the build hermetic; ``--check``
plus the ``i18n-catalogs-in-sync`` pre-commit hook keep it from drifting.

Usage:
    python3 scripts/generate_i18n_catalogs.py            # write
    python3 scripts/generate_i18n_catalogs.py --check    # verify only
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE_DIR = REPO_ROOT / "backend" / "config" / "i18n"
TARGET_DIR = REPO_ROOT / "frontend" / "src" / "i18n" / "catalogs"

HEADER = (
    "// GENERATED by scripts/generate_i18n_catalogs.py - do not edit.\n"
    "// Source: backend/config/i18n/{name}.yaml\n"
)


def render(path: Path) -> str:
    """One catalog as formatted JSON (stable key order, trailing newline)."""
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    return json.dumps(data, ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero when a catalog is missing or out of date",
    )
    args = parser.parse_args()

    sources = sorted(SOURCE_DIR.glob("*.yaml"))
    if not sources:
        print(f"No catalogs found in {SOURCE_DIR}", file=sys.stderr)
        return 1

    TARGET_DIR.mkdir(parents=True, exist_ok=True)
    stale: list[str] = []
    for source in sources:
        target = TARGET_DIR / f"{source.stem}.json"
        rendered = render(source)
        if args.check:
            current = target.read_text(encoding="utf-8") if target.exists() else ""
            if current != rendered:
                stale.append(source.stem)
            continue
        target.write_text(rendered, encoding="utf-8")

    if args.check:
        if stale:
            print(
                "i18n catalogs out of date: "
                + ", ".join(stale)
                + "\nRun: python3 scripts/generate_i18n_catalogs.py",
                file=sys.stderr,
            )
            return 1
        print(f"i18n catalogs in sync ({len(sources)} languages)")
        return 0

    print(f"Wrote {len(sources)} catalogs to {TARGET_DIR.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
