"""initial topos schema

Revision ID: 0b846e96f438
Revises:
Create Date: 2026-05-22 11:21:44.532940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b846e96f438'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('parent_path', sa.String(length=500), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_parent_path'), ['parent_path'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_path'), ['path'], unique=True)

    op.create_table('containers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('FOLDER', 'BOX', name='containertype'), nullable=False),
    sa.Column('owner', sa.Enum('SELF', 'PARENTS', 'SHARED', name='owner'), nullable=False),
    sa.Column('label', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('size_group', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('containers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_containers_external_id'), ['external_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_containers_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_containers_owner'), ['owner'], unique=False)
        batch_op.create_index(batch_op.f('ix_containers_type'), ['type'], unique=False)

    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('container_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('priority', sa.Enum('NONE', 'LOW', 'MEDIUM', 'HIGH', 'VERY_HIGH', name='priority'), nullable=False),
    sa.Column('category_path', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_category_path'), ['category_path'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_container_id'), ['container_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_priority'), ['priority'], unique=False)

    op.create_table('actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'DONE', 'ARCHIVED', name='actionstatus'), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actions_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_actions_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actions_status'))
        batch_op.drop_index(batch_op.f('ix_actions_item_id'))

    op.drop_table('actions')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_priority'))
        batch_op.drop_index(batch_op.f('ix_items_container_id'))
        batch_op.drop_index(batch_op.f('ix_items_category_path'))

    op.drop_table('items')
    with op.batch_alter_table('containers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_containers_type'))
        batch_op.drop_index(batch_op.f('ix_containers_owner'))
        batch_op.drop_index(batch_op.f('ix_containers_location'))
        batch_op.drop_index(batch_op.f('ix_containers_external_id'))

    op.drop_table('containers')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_path'))
        batch_op.drop_index(batch_op.f('ix_categories_parent_path'))

    op.drop_table('categories')
    # ### end Alembic commands ###
