"""initial schema

Revision ID: fd1e9e5b4d91
Revises:
Create Date: 2026-04-04 09:56:37.439492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd1e9e5b4d91'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('subtitle', sa.String(length=500), nullable=True),
    sa.Column('author', sa.String(length=300), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('series', sa.String(length=300), nullable=True),
    sa.Column('series_index', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('edition', sa.String(length=100), nullable=True),
    sa.Column('publisher', sa.String(length=300), nullable=True),
    sa.Column('publisher_city', sa.String(length=200), nullable=True),
    sa.Column('publish_date', sa.String(length=20), nullable=True),
    sa.Column('isbn_ebook', sa.String(length=20), nullable=True),
    sa.Column('isbn_paperback', sa.String(length=20), nullable=True),
    sa.Column('isbn_hardcover', sa.String(length=20), nullable=True),
    sa.Column('asin_ebook', sa.String(length=20), nullable=True),
    sa.Column('asin_paperback', sa.String(length=20), nullable=True),
    sa.Column('asin_hardcover', sa.String(length=20), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('html_description', sa.Text(), nullable=True),
    sa.Column('backpage_description', sa.Text(), nullable=True),
    sa.Column('backpage_author_bio', sa.Text(), nullable=True),
    sa.Column('cover_image', sa.String(length=500), nullable=True),
    sa.Column('custom_css', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('book_id', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapters',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('book_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('chapter_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chapters')
    op.drop_table('assets')
    op.drop_table('books')
    # ### end Alembic commands ###
